default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DATABASE_HOST')  { 'localhost' } %>
  port: <%= (ENV['DATABASE_PORT'] && !ENV['DATABASE_PORT'].empty?) ? ENV['DATABASE_PORT'] : 5432 %>
  username: <%= ENV.fetch('DATABASE_USERNAME')  { 'postgres' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD')  { 'postgres' } %>
  sslmode: <%= (ENV['DATABASE_SSLMODE'] && !ENV['DATABASE_SSLMODE'].empty?) ? ENV['DATABASE_SSLMODE'] : nil %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: workshop_development

test:
  <<: *default
  database: workshop_test

production:
  <<: *default
  database: <%= (ENV['DATABASE_NAME'] && !ENV['DATABASE_NAME'].empty?) ? ENV['DATABASE_NAME'] : 'workshop_production' %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
