apiVersion: v1
kind: Secret
metadata:
  name: web-secret
  namespace: workshop
type: Opaque
data:
  DATABASE_HOST: "${DATABASE_HOST}"
  DATABASE_USERNAME: "${DATABASE_USERNAME}"
  DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
  JWT_SECRET: "${JWT_SECRET}"
  SMTP_USERNAME: "${SMTP_USERNAME}"
  SMTP_PASSWORD: "${SMTP_PASSWORD}"
  SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
  INTERNAL_AUTH_TOKEN: "${INTERNAL_AUTH_TOKEN}"
