apiVersion: v1
kind: Secret
metadata:
  name: web-secret
  namespace: workshop
type: Opaque
stringData:
  DATABASE_HOST: "${DATABASE_HOST}"
  DATABASE_PORT: "${DATABASE_PORT}"
  DATABASE_NAME: "${DATABASE_NAME}"
  DATABASE_SSLMODE: "${DATABASE_SSLMODE}"
  DATABASE_USERNAME: "${DATABASE_USERNAME}"
  DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
  JWT_SECRET: "${JWT_SECRET}"
  SMTP_USERNAME: "${SMTP_USERNAME}"
  SMTP_PASSWORD: "${SMTP_PASSWORD}"
  SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
  AWS_REGION: "${AWS_REGION}"
  EKS_CLUSTER_NAME: "${EKS_CLUSTER_NAME}"
  ECR_REPOSITORY: "${ECR_REPOSITORY}"
